# begin het maken van de selectie query
# Voor de "{" is het gedeelte van de project. Met een ster nemen we alle variabelen mee die worden gedefinieerd in de query
select * {

    # We vragen alle triples terug. De namen van de variabelen maken niet uit, maar door het "?" geven we aan dat
    # alles variable is en dus elke patroon in triple vorm moet worden teruggegeven.
    ?subject ?predicaat ?object
}

# beperk de output tot 5 voorbeelden. Merk op dat we anders de hele dataset opvragen!
limit 5
