# definities als verkorte schrijfwijze
prefix schema: <http://schema.org/>

# begin het maken van de selectie
select ?boek {
  
    # selecteer alle titels van het type 'boek'
    ?boek a schema:Book
}

# beperk het aantal resultaten tot 5
limit 5

