# definities als verkorte schrijfwijze
prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>

# begin het maken van de selectie
# de term 'distinct' zorgt er voor dat dubbele resultaten onderdrukt worden
select distinct ?onderwerp ?uri {

    # Door de "+" vragen we alle uri's op die
    # als onderliggende of door tussennode onderliggende term voor dieren hebben 
    ?uri skos:broader+ <http://data.bibliotheken.nl/id/thes/p075635178> .

    # en het label bij deze uri ophalen
    ?uri skos:prefLabel ?onderwerp .

}
order by ?onderwerp
limit 10
