PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX edm: <http://www.europeana.eu/schemas/edm/>

SELECT distinct (sample(?maker_name) as ?name) (count(?cho) as ?aantal) ?maker 
{
  ?cho a edm:ProvidedCHO .
  ?cho dc:creator ?maker .
  ?maker skos:prefLabel ?maker_name .
  ?cho dc:type/skos:prefLabel "schilderij"@nl .
  #filter(langMatches(lang(?maker), "nl"))
  filter(?maker != <http://hdl.handle.net/10934/RM0001.PEOPLE.0>)
} order by desc(?aantal) limit 10