# definities als verkorte schrijfwijze
prefix schema: <http://schema.org/>

# toon alle opgehaalde velden 
select * {
  
  # zorg dat we alleen de resultaten uit deze dataset ('graph') krijgen 
  graph <https://data.netwerkdigitaalerfgoed.nl/enno/wd-nta-geslacht/graphs/default> 
  {
     ?nta ?eigenschap ?waarde 
  }
}
# sorteer het resultaat op het veld '?nta'
order by ?nta

# beperk het aantal resultaten tot 6
limit 6